add frontend pipeline

diff --git a/backend/Jenkinsfile b/backend/Jenkinsfile
--- a/backend/Jenkinsfile
+++ b/backend/Jenkinsfile
@@ -188,18 +188,18 @@ spec:
             steps {
               container('trivy'){
                   dir('backend'){
-                            sh '''
-                            trivy image --no-progress --severity MEDIUM,HIGH,CRITICAL \
-                                        --skip-files ".npm/_cacache/*" \
-                                        --timeout 10m thanh8804/smash-shop-backend-image:$IMAGE_TAG > trivy-image.txt 2>&1
-                            cat trivy-image.txt
-                            '''
-                            sh '''
-                            CRITICAL_COUNT=$(grep -oP 'CRITICAL: \\K[0-9]+' trivy-image.txt | head -1)
-                            if [ "$CRITICAL_COUNT" != "" ] && [ "$CRITICAL_COUNT" -gt 0 ]; then
-                                echo "Critical vulnerabilities found in source scan ($CRITICAL_COUNT), failing pipeline"
-                                exit 1
-                            fi
+                        sh '''
+                        trivy image --no-progress --severity MEDIUM,HIGH,CRITICAL \
+                                    --skip-files ".npm/_cacache/*" \
+                                    --timeout 10m thanh8804/smash-shop-backend-image:$IMAGE_TAG > trivy-image.txt 2>&1
+                        cat trivy-image.txt
+                        '''
+                        sh '''
+                        CRITICAL_COUNT=$(grep -oP 'CRITICAL: \\K[0-9]+' trivy-image.txt | head -1)
+                        if [ "$CRITICAL_COUNT" != "" ] && [ "$CRITICAL_COUNT" -gt 0 ]; then
+                            echo "Critical vulnerabilities found in source scan ($CRITICAL_COUNT), failing pipeline"
+                            exit 1
+                        fi
                         '''
                     }
                 }
